---
# Install and configure auditd to provide additional logging

- name: "auditd : ensure auditd package is installed"
  package:
    name: "auditd"
    state: present
    update_cache: yes
  become: yes

- name: "auditd : configure auditd"
  template:
    src: "audit.rules.j2"
    dest: "/etc/audit/audit.rules"
    mode: '0640'
    backup: yes
  notify:
    - security restart auditd
  become: yes

- name: "auditd : install real-time interface for the audit system"
  package:
    name: "audispd-plugins"
    state: present
    update_cache: yes
  when: "security_audit_remote_sending|bool and ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 22"
  become: yes

- name: "auditd : configure audit remote sending"
  template:
    src: "audisp-remote.conf.j2"
    dest: "/etc{% if ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 22 %}/audit{% else %}/audisp{% endif %}/audisp-remote.conf"
    mode: '0640'
    backup: yes
  when: security_audit_remote_sending|bool
  notify:
    - security restart auditd
  become: yes

- name: "auditd : ensure auditd is started"
  service:
    name: "auditd"
    state: started
    enabled: yes
  become: yes
