---
# Configure PAM for with additional security options
#
# Given the complexity and potential for disaster associated with modifying
# existing PAM configurations, the tasks below back up and REPLACE the
# PAM configuration.
#
# If you have a custom PAM configuration that cannot be met by this role, you
# should set `security_pam_harden: no` which will skip these tasks.
#

- name: "pam : install password quality enforcement tools"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - libpam-pwquality
    - cracklib-runtime
  become: yes

- name: "pam : configure faillock"
  ansible.builtin.template:
    src: faillock.conf.j2
    dest: /etc/security/faillock.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 22"
  become: yes
  tags:
    - security_pam_config

- name: "pam : define the common-account configuration"
  ansible.builtin.template:
    src: common-account.j2
    dest: /etc/pam.d/common-account
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  tags:
    - security_pam_config

- name: "pam : define the common-auth configuration"
  ansible.builtin.template:
    src: common-auth.j2
    dest: /etc/pam.d/common-auth
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  tags:
    - security_pam_config

- name: "pam : define the common-password configuration"
  ansible.builtin.template:
    src: common-password.j2
    dest: /etc/pam.d/common-password
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  tags:
    - security_pam_config

- name: "pam : define the common-session configuration"
  ansible.builtin.template:
    src: common-session.j2
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  tags:
    - security_pam_config

- name: "pam : define the common-session-noninteractive configuration"
  ansible.builtin.template:
    src: common-session-noninteractive.j2
    dest: /etc/pam.d/common-session-noninteractive
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  tags:
    - security_pam_config

