---
# Set password restrictions/standards/complexity

##
## Update /etc/login.defs
##
## login.defs configures the shadow password tool
##

- name: "passwords : set password maximum days"
  lineinfile:
    path: /etc/login.defs
    line: "PASS_MAX_DAYS    {{ security_password_max_days }}"
    regex: '^(#?)PASS_MAX_DAYS\s'
  become: yes

- name: "passwords : set password minimum days"
  lineinfile:
    path: /etc/login.defs
    line: "PASS_MIN_DAYS    {{ security_password_min_days }}"
    regex: '^(#?)PASS_MIN_DAYS\s'
  become: yes

- name: "passwords : prevent login if unable to cd to home directory"
  lineinfile:
    path: /etc/login.defs
    line: "DEFAULT_HOME    no"
    regex: '^(#?)DEFAULT_HOME\s'
  become: yes

- name: "passwords : specify the encryption method"
  lineinfile:
    path: /etc/login.defs
    line: "ENCRYPT_METHOD    SHA512"
    regex: '^(#?)ENCRYPT_METHOD\s'
  become: yes

# This will likely be superseeded by PAM but is a good fallback
- name: "passwords : maximum login retries"
  lineinfile:
    path: /etc/login.defs
    line: "LOGIN_RETRIES    {{ security_password_max_retries }}"
    regex: '^(#?)LOGIN_RETRIES\s'
  become: yes

# Maximum amount of time in seconds for the login
- name: "passwords : maximum login time"
  lineinfile:
    path: /etc/login.defs
    line: "LOGIN_TIMEOUT    {{ security_password_login_timeout }}"
    regex: '^(#?)LOGIN_TIMEOUT\s'
  become: yes

# Number of seconds before being allowed another attempt after a login failure
# ERROR: This is absolute and causes an error if set
- name: "passwords : set the fail delay"
  lineinfile:
    path: /etc/login.defs
    line: "FAIL_DELAY    {{ security_password_fail_delay }}"
    regex: '^(#?)FAIL_DELAY\s'
  become: yes

- name: "passwords : set the quality standards"
  template:
    src: pwquality.conf.j2
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
